import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronLeft, LayoutDashboard, Minus, Package, Plus, Search, ShoppingBag, Trash2, Truck, X } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type StoreProduct = { id: number; name: string; sku: string; price: number; stock: number; description: string | null; imageUrl: string | null; category: string | null };
type CartItem = StoreProduct & { quantity: number };

const formatPrice = (value: number) => new Intl.NumberFormat("ar-YE").format(value);

function ProductVisual({ product }: { product: StoreProduct }) {
  return product.imageUrl ? <img src={product.imageUrl} alt={product.name} /> : <div className="store-product-art"><Package size={38} /><span>{product.category || "Milano"}</span></div>;
}

function StoreHeader({ cartCount, onCart, onHome, search, setSearch }: { cartCount: number; onCart: () => void; onHome: () => void; search: string; setSearch: (value: string) => void }) {
  return <header className="store-header"><button className="store-brand" onClick={onHome} aria-label="العودة إلى المتجر"><span className="store-brand-mark">م</span><span><strong>ميلانو</strong><small>متجر ميلانو</small></span></button><div className="store-search"><Search size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث عن منتج أو رمز المنتج..." /></div><div className="store-header-actions"><button className="store-admin-link" onClick={() => { window.location.href = "/admin"; }}><LayoutDashboard size={16} /><span>لوحة التحكم</span></button><button className="store-cart-button" onClick={onCart}><ShoppingBag size={19} /><span>السلة</span>{cartCount > 0 && <b>{cartCount}</b>}</button></div></header>;
}

export default function Storefront() {
  const [location, setLocation] = useLocation();
  const [search, setSearch] = useState("");
  const [cart, setCart] = useState<CartItem[]>(() => { try { return JSON.parse(localStorage.getItem("milano-cart") || "[]"); } catch { return []; } });
  const [checkoutDone, setCheckoutDone] = useState(false);
  const productsQuery = trpc.store.products.useQuery(undefined, { staleTime: 0, refetchInterval: 3_000 });
  const createOrder = trpc.store.createOrder.useMutation({ onSuccess: () => { setCheckoutDone(true); setCart([]); localStorage.removeItem("milano-cart"); toast.success("تم استلام طلبك بنجاح"); }, onError: () => toast.error("تعذر إرسال الطلب، حاول مرة أخرى") });
  const updateCart = (next: CartItem[]) => { setCart(next); localStorage.setItem("milano-cart", JSON.stringify(next)); };
  const products = (productsQuery.data || []) as StoreProduct[];
  const filtered = useMemo(() => products.filter(product => `${product.name} ${product.sku}`.toLowerCase().includes(search.trim().toLowerCase())), [products, search]);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0);
  const addToCart = (product: StoreProduct) => { if (product.stock < 1) return toast.error("هذا المنتج غير متوفر حالياً"); const existing = cart.find(item => item.id === product.id); updateCart(existing ? cart.map(item => item.id === product.id ? { ...item, quantity: Math.min(item.quantity + 1, product.stock) } : item) : [...cart, { ...product, quantity: 1 }]); toast.success("تمت إضافة المنتج إلى السلة"); };
  const changeQuantity = (id: number, delta: number) => updateCart(cart.map(item => item.id === id ? { ...item, quantity: Math.max(0, Math.min(item.quantity + delta, item.stock)) } : item).filter(item => item.quantity > 0));
  const isCheckout = location === "/checkout";
  if (checkoutDone) return <div className="store-app" dir="rtl"><div className="store-success"><CheckCircle2 size={58} /><h1>تم تأكيد طلبك</h1><p>شكراً لتسوقك من متجر ميلانو. سيتواصل معك فريقنا لتأكيد التوصيل.</p><button className="store-primary" onClick={() => { setCheckoutDone(false); setLocation("/"); }}>العودة إلى المتجر</button></div></div>;
  return <div className="store-app" dir="rtl"><StoreHeader cartCount={cartCount} onCart={() => setLocation("/checkout")} onHome={() => setLocation("/")} search={search} setSearch={setSearch} />
    {!isCheckout ? <main className="store-main"><section className="store-hero"><div><span className="store-kicker">تجربة ميلانو الجديدة</span><h1>اختياراتك اليومية،<br /><em>بلمسة ميلانو.</em></h1><p>اكتشف منتجات مختارة بعناية، اطلب بسهولة، واستمتع بتجربة شراء سلسة من أول خطوة حتى التوصيل.</p><button className="store-primary" onClick={() => document.getElementById("store-catalog")?.scrollIntoView({ behavior: "smooth" })}>تصفح المنتجات <ArrowLeft size={16} /></button></div><div className="store-hero-shape"><ShoppingBag size={84} /><span>MILANO<br />COLLECTION</span></div></section><section id="store-catalog" className="store-catalog"><div className="store-section-heading"><div><span className="store-kicker">كتالوج المتجر</span><h2>منتجات مختارة لك</h2><p>{products.length ? `${products.length} منتجات متاحة الآن` : "أضف أول منتج من لوحة التحكم ليظهر هنا مباشرة"}</p></div><div className="store-category-pills"><button className="active">الكل</button><button>الأكثر طلباً</button><button>وصل حديثاً</button></div></div>{productsQuery.isLoading ? <div className="store-empty"><div className="store-loading" /><p>جاري تحميل الكتالوج...</p></div> : filtered.length ? <div className="store-product-grid">{filtered.map(product => <article className="store-product-card" key={product.id}><div className="store-product-image"><ProductVisual product={product} /><span className={product.stock === 0 ? "out" : "available"}>{product.stock === 0 ? "نفد المخزون" : "متوفر"}</span></div><div className="store-product-body"><small>{product.category || "منتجات ميلانو"}</small><h3>{product.name}</h3><p>{product.description || "منتج مختار بجودة عالية وتجربة استخدام مميزة."}</p><div className="store-product-bottom"><strong>{formatPrice(product.price)} <small>ريال يمني</small></strong><button disabled={product.stock === 0} onClick={() => addToCart(product)}><Plus size={16} />إضافة</button></div></div></article>)}</div> : <div className="store-empty"><Package size={38} /><h3>{products.length ? "لا توجد نتائج مطابقة" : "الكتالوج جاهز لاستقبال منتجاتك"}</h3><p>{products.length ? "جرّب البحث باسم مختلف أو رمز المنتج." : "عند إضافة منتج من /admin سيظهر هنا تلقائياً من قاعدة البيانات المشتركة."}</p></div>}</section></main> : <Checkout cart={cart} total={total} changeQuantity={changeQuantity} onBack={() => setLocation("/")} onSubmit={(data) => createOrder.mutate({ ...data, items: cart.map(item => ({ productId: item.id, name: item.name, quantity: item.quantity, price: item.price })), total })} isSubmitting={createOrder.isPending} />}
  </div>;
}

function Checkout({ cart, total, changeQuantity, onBack, onSubmit, isSubmitting }: { cart: CartItem[]; total: number; changeQuantity: (id: number, delta: number) => void; onBack: () => void; onSubmit: (data: { customerName: string; customerPhone: string; customerAddress: string }) => void; isSubmitting: boolean }) {
  const [form, setForm] = useState({ customerName: "", customerPhone: "", customerAddress: "" });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!cart.length) return toast.error("السلة فارغة"); if (Object.values(form).some(value => !value.trim())) return toast.error("يرجى إكمال بيانات التوصيل"); onSubmit(form); };
  return <main className="checkout-main"><button className="store-back-link" onClick={onBack}><ChevronLeft size={17} /> العودة للمتجر</button><div className="checkout-heading"><div><span className="store-kicker">خطوة أخيرة</span><h1>إتمام الطلب</h1><p>أدخل بياناتك وسنجهز طلبك للتوصيل.</p></div><div className="checkout-step"><span>1</span> السلة <ArrowLeft size={13} /><span className="current">2</span> البيانات</div></div><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><div className="checkout-card"><h2>بيانات التوصيل</h2><label>الاسم الكامل<input value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })} placeholder="مثال: أحمد محمد" /></label><label>رقم الهاتف<input value={form.customerPhone} onChange={e => setForm({ ...form, customerPhone: e.target.value })} placeholder="07xxxxxxxx" dir="ltr" /></label><label>العنوان بالتفصيل<textarea value={form.customerAddress} onChange={e => setForm({ ...form, customerAddress: e.target.value })} placeholder="المدينة، الحي، الشارع، وأي تفاصيل تساعد في الوصول" /></label></div><div className="checkout-card"><h2>طريقة الدفع</h2><div className="payment-choice active"><span className="payment-radio" /><div><strong>الدفع عند الاستلام</strong><small>ادفع نقداً عند وصول طلبك</small></div><Truck size={22} /></div></div><button className="store-primary checkout-submit" disabled={isSubmitting}>{isSubmitting ? "جاري إرسال الطلب..." : "تأكيد الطلب"}<ArrowLeft size={16} /></button></form><aside className="checkout-summary"><div className="checkout-card"><h2>ملخص السلة <span>{cart.length} منتجات</span></h2>{cart.length ? cart.map(item => <div className="checkout-item" key={item.id}><div className="checkout-item-art"><Package size={18} /></div><div><strong>{item.name}</strong><small>{formatPrice(item.price)} ريال × {item.quantity}</small></div><div className="quantity-control-store"><button type="button" onClick={() => changeQuantity(item.id, -1)}><Minus size={12} /></button><b>{item.quantity}</b><button type="button" onClick={() => changeQuantity(item.id, 1)}><Plus size={12} /></button></div></div>) : <div className="empty-cart"><ShoppingBag size={30} /><p>لم تضف منتجات إلى السلة بعد.</p></div>}<div className="checkout-total"><span>الإجمالي</span><strong>{formatPrice(total)} <small>ريال يمني</small></strong></div></div></aside></div></main>;
}
